development:
  adapter: mysql
  database: fever_development
  username: root
  password: saurabh
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql
  database: fever_test
  username: root
  password: saurabh
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  database: fever_production
  username: root
  password: saurabh
  socket: /var/run/mysqld/mysqld.sock
